# Generated by Django 5.2.3 on 2025-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
