# Generated by Django 5.2.3 on 2025-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='answer',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
