# Generated by Django 5.2.3 on 2025-06-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='designorder',
            name='design_type',
        ),
        migrations.RemoveField(
            model_name='designorder',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='designorder',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='designorder',
            name='size',
        ),
        migrations.AddField(
            model_name='designorder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='design_uploads/'),
        ),
        migrations.AddField(
            model_name='designorder',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designorder',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
