# Generated by Django 5.2.3 on 2025-07-07 16:31

import project_5.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_designorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeddesign',
            name='file',
            field=models.FileField(storage=project_5.custom_storages.MediaStorage(), upload_to='completed_designs/'),
        ),
        migrations.AlterField(
            model_name='designorder',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=project_5.custom_storages.MediaStorage(), upload_to='design_uploads/'),
        ),
    ]
