# Generated by Django 5.2.3 on 2025-07-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_completeddesign_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
