# Generated by Django 5.2.3 on 2025-07-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_designtype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='designorder',
            name='design_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.designtype'),
        ),
    ]
