# Generated by Django 5.2.3 on 2025-07-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_designorder_design_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddesign',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
