# Generated by Django 5.2.3 on 2025-07-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_completeddesign_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddesign',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
