# Generated by Django 5.2.3 on 2025-07-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_completeddesign_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeddesign',
            name='is_paid',
        ),
    ]
