# Generated by Django 5.2.3 on 2025-07-07 12:48

import project_5.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=project_5.custom_storages.MediaStorage(), upload_to='product_images/'),
        ),
    ]
